# Generated by Django 3.2.7 on 2021-10-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211001_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('a', 'A'), ('a1', 'A1'), ('b', 'B'), ('be', 'BE'), ('c1', 'C1'), ('c1e', 'C1E'), ('c', 'C'), ('ce', 'CE'), ('d1', 'D1'), ('d1e', 'D1E'), ('d', 'D'), ('de', 'DE')], default='b', max_length=3, unique=True),
        ),
    ]
