# Generated by Django 3.2.7 on 2021-10-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_category_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='category',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='driver',
        ),
        migrations.AddField(
            model_name='driver',
            name='categories',
            field=models.ManyToManyField(to='app.Category'),
        ),
        migrations.AddField(
            model_name='transport',
            name='drivers',
            field=models.ManyToManyField(to='app.Driver'),
        ),
    ]
